### ISSUE TITLE
Impossible to find correct entity

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-pdp#12]
When mulitple entities (IdP,SP) have the same name, there is no way to distinguish between them in the PDP UI.  For example:

![screenshot_20170607_154444_1598x1390](https://user-images.githubusercontent.com/1461740/26881649-5d384c24-4b98-11e7-81c7-321b0cc6b27f.png)

It would be nice to show at least the status (prod or test) or the entityid.

**Comment by thijskh** [comment]
Fixed in the manage migration
