### ISSUE TITLE
Allowing access for multiple teams is always AND

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-pdp#13]
When allowing access to multiple teams, the current behaviour seems to be that the user needs to be a member of _all_ specified teams (rather than of at least one team), even though the rules are "OR" and the automatically generated description suggests that the user needs to be a member of either team.

I'm not entirely sure if this is intended or whether this is a bug.  Either way, the UI is rather unclear on this point.  If it is intended, than please add another way to allow access to more than one team.

**Comment by thijskh** [comment]
This is most certainly no longer the case
