### ISSUE TITLE
Policy Not applicable

### ISSUE THREAD

**Issue by jainh** [OpenConext/OpenConext-pdp#14]
Hi,
Has anyone seen an issue that after creating a policy through PDP-gui and then immediately requesting pdp-server with right set of request for permit decision resulting in NotApplicable result.

**Comment by quartje** [comment]
Sorry for this late reply! The PDP policies are cached, changing a policy will take some time to refresh. This behaviour can be configured in the application.yml: https://github.com/OpenConext/OpenConext-pdp/blob/master/pdp-server/src/main/resources/application.properties#L38
