### ISSUE TITLE
Issue with logback-file

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-pdp#16]
With a `/src/main/resources/logback.xml` file in place, it's become useless to set `logging.config=file:/example-dir/logback.xml` because the one in the class-path will take precedence over the application.properties setting.
It took me quite a while to figure out why the app was trying to start with the default logback-settings, while other apps like Manage and AA didn't give me this issue. Obviously, they don't include a default logback.xml, so my suggestion would be to either remove it from this repo, move it to extra/logback.xml or exclude it from the jar using an exclusion in pom.xml

**Comment by oharsta** [comment]
Deleted the `src/main/resources/logback/xml` in https://github.com/OpenConext/OpenConext-pdp/commit/2d79b424d00425db1222c0744395d429d5453b47
