### ISSUE TITLE
Violations page not working

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/OpenConext-pdp#18]
When viewing violations on a policy, I get "The PDP application is currently unavailable".
Global violations view (/violations) works, specific ones fail (/violations/123)
This started after updating from 2.0.1 to 2.0.2.

I have verified that the issue still exists on master and that a rollback to 2.0.1 fixes it.

**Comment by oharsta** [comment]
Bug confirmed and fixed in https://github.com/OpenConext/OpenConext-pdp/commit/e193ec5016717cf94098d903a4303cea64a20b2f#diff-2a200e386e06e5e92f41cd589ae7dcf5.
