### ISSUE TITLE
Hangs on loading external resource

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-pdp#2]
On Acc, the PDP hangs on loading an external resource `rollbar.min.js`.  It might be worth considering not loading any external resources at al, to increase privacy.

![pdp1](https://cloud.githubusercontent.com/assets/1461740/12395201/a2195c06-be00-11e5-88a2-7c675ed50226.png)

**Comment by oharsta** [comment]
Rollbar has been removed from PDP
