### ISSUE TITLE
Make more error-text editable for user

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-pdp#228]
[This issue is imported from pivotal - Originaly created at Feb 14, 2018 by Raoul Teeuwen](https://www.pivotaltracker.com/story/show/155229004)

Uit https://jira.surfnet.nl/browse/CXT-27245: "Ik vroeg me nog wel af wat de eventuele mogelijkheden zijn om de tekst van de melding (zoals deze aan gebruikers wordt getoond wanneer zij geen toegang hebben) verder aan te passen.
Het gaat hier dan om de tekst: You have successfully logged in at your institution, but unfortunately you cannot use this service (the ‘Service Provider’) because you have no access [...] (zie ook attachment).
Met name de bewoording in het stukje [...] 
you cannot use this service (the ‘Service Provider’) [...] zouden we graag anders zien; daarnaast zou het wellicht praktisch zijn als we hier bijvoorbeeld ook een hyperlink of e-mailadres zouden kunnen weergeven zodat we onze gebruikers net iets beter kunnen opvangen en/of doorverwijzen naar een plek met meer tekst en uitleg."

Om bovenstaande vraag mogelijk te maken is het idee om twee extra invoervelden te maken in de PDP Gui: Contactgegevens en een support URL. Als deze worden ingevuld moet dit meegegeven worden in het XACML bericht richting EB, die, als de waarde is ingevuld, vervolgens dat kan weergeven in de deny message

De zin "Please contact your institutions helpdesk" wordt dan in het geval dat de contactgegevens zijn ingevuld worden: "Please contact $CONTACTGEGEVENS". Dit laatste moet in EB worden geregeld. 

Als de URL wordt ingevuld komt er in de EB deny message te staan: "More information available at $URL"

**Comment by thijskh** [comment]
Will close for now, we can reprioritize if more demand surfaces
