### ISSUE TITLE
Add option to go to URL instead of show error

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-pdp#229]
[This issue is imported from pivotal - Originaly created at Jul 3, 2017 by Raoul Teeuwen](https://www.pivotaltracker.com/story/show/148213091)

In some cases, IdP\'s rather show users a web page they control themselves, for instance to have more room to explain the situation. So the idea is to add an option to go to a IdP specified URL instead of showing a block-message.

For the PDP this means that we\'d like to be able to configure a redirect URL, which can be transmitted in the XACML message so that EB can 302 to this page.

**Comment by thijskh** [comment]
Will close for now, we can reprioritize if more demand surfaces
