### ISSUE TITLE
trailing spaces in attribute values

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-pdp#3]
Please remove trailing and leading spaces in attribute values when submitting a policy.  I can't think of a situation in which such spaces would actually make sense, and they do get in the way in the current UI, in particularly when copy-and-pasting SURFconext Teams identifiers: it easy and unnoticeable to add an extra space, which gives very hard-to-debug issues.

**Comment by oharsta** [comment]
https://github.com/OpenConext/OpenConext-pdp/commit/c9be062817b45807af0cfe44c7d78f59fe00753f
