### ISSUE TITLE
dev to prod migration results in hard to diagnose errors

### ISSUE THREAD

**Issue by mrvanes** [OpenConext/OpenConext-pdp#4]
When PDP server is tested in spring.profiles.active=dev mode, the database is filled with test rules, referring to test IdP's and SP's but in this mode changes do not persists server restarts.
Once changed to prod, these policies remain, but are checked against the real metadata export from SR. This results in a hard to diagnose "Something went wrong when opening this page." Maybe a more graceful acceptance of unresolvable entityID's could relieve this pain for admins that try to bootstrap PDP (manually).

**Comment by tvdijen** [comment]
I should totally read up on open issues before playing around with this stuff :D
I didn't get a "something went wrong" message, just an empty policy overview.. After removing all test-entities from the database, my policy showed up in the overview.

**Comment by thijskh** [comment]
No longer relevant with GUI deprecation
