### ISSUE TITLE
Translations contain references to SURFnet

### ISSUE THREAD

**Issue by mrvanes** [OpenConext/OpenConext-pdp#5]
Both pdp-gui/src/javascripts/locale/en.js and nl.js contain 11 references to SURF. ROLE_ADMIN eg is translated as "SURFnet Admin". Should only contain references to OpenConext.

**Comment by thijskh** [comment]
Would it be possible to use a variable, e.g. `%PRODUCTNAME` in the templates? Then the app could set this once in config and we can reference it in templates like "Please contact %PRODUCTNAME% Support".
