### ISSUE TITLE
Service Registry

### ISSUE THREAD

**Issue by jainh** [OpenConext/OpenConext-pdp#8]
1) Is it possible to use OpenContext-pdp as a standalone pdp-engine ?  what is the use of service registry dependency ?

2) pdp-gui is an alternative to PAP in openaz ?

**Comment by thijskh** [comment]
1) Yes. The required list of IdP's and SP's comes in JSON format, so if you use anything that can produce the same JSON format you can make it work. SR is an existing implementation that provides that format, but there should be no problem implementing your own.

2) It is indeed a PAP.
