### ISSUE TITLE
OIDC idp

### ISSUE THREAD

**Issue by jainh** [OpenConext/OpenConext-pdp#9]
Can i put mitreid connect as an idp in the configuration ? if  yes what information do i need to put in the configuration for idp ?

**Comment by thijskh** [comment]
The OpenConext platform currently only supports SAML 2.0 IdP's. The PEP is included in the Engineblock component which is a SAML 2.0 only proxy. Of course, if you choose to use OpenConext-pdp with another authentication gateway in which you implement your PEP, you're free to use any protocol you like.
